title: Marx Wang
description: PhD Candidate @ UW iSchool
url: "https://marxvwang.com"
baseurl: ""
keywords: hci, llm alignment, affective computing, conversational ai

markdown: kramdown
highlighter: rouge
permalink: pretty

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - README.md
  - "Marx Wang's Resume.pdf"

sass:
  sass_dir: _sass
  style: compressed

author:
  first_name: Marx
  last_name: Wang
  email: marxwang@uw.edu
  role: PhD Candidate
  affiliation: University of Washington
  department: Information School
  image: prof_pic.jpg
  image_circular: false
  initials: MW
  subtitle: 'PhD Candidate @ <a href="https://ischool.uw.edu/">UW iSchool</a>'

social:
  github: marx1108
  scholar: YOUR_GOOGLE_SCHOLAR_ID
  linkedin: marxw
  twitter: ""

plugins:
  - jekyll-seo-tag
